version:
  name: velociraptor
  version: 0.7.0-2
  commit: 82f2cad
  build_time: "2023-09-10T15:23:01Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/6137985901
  compiler: go1.21.0
Client:
  server_urls:
  - https://logger:9000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRANcJLBYb0G3FWV6LntCQGS8wDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDQyODA1NDYyNloXDTMy
    MDQyNTA1NDYyNlowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4JpgvMSKzxD7kpY93u1QLvplZ2iWtZ12
    cW3SgeUfINjz3f12W9UF6tRkoajSMbJS/MMD4+qpBmMHVKnjqnQ4UiGb5AQY8esi
    JeqAvPUeOWGelMdvVwSEtNYkVats1S2HRn2DyJcEhX+2TMtNxWYGgh2NioXR+7hr
    LcX8cWwEHY6K13pqpQ87IfI9U9oMEWiV6jOah55XrRukn0swSV+dgvi4QByMwLtd
    6tDMdfJcs4qcwacawfpyM1ayF+GOA8OptZIAvwH5Ti7wrLU6oQW/vwimWDpVPJ0B
    xB9+ie6Uc0Iu0ymH/kTD18/oP+ULxAT/B2Lb6NTommuttoDz8BT1kwIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUZi5aKA/apJbEQQNZMT782wPX
    xUswKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBALx8CvbKNk9Pg4tWA+tWClg/UU3gBwkqHUcbMImJOSPq
    DBAkw+E3ZEuKkZkQq1HrWYhPzW2AAUwvvd98wYnXjulZ4Z92Z3YZ6I09gYREnwxb
    a0PCyQWnfFprLDJuQf5zQOSVZ0X1p52xED9A3YZeHvxPsfcmb78xqniPQZqyRXC2
    qQhpW2gUrlmU1tOQKAQ/w/+D74cxdRnlxFpo6uhxfaxdwXUyeWW+w3w10ys+qkxI
    6gMK7QG0CndVdJUXJmQcoYpLEoM3IcYLE/e5i2Sxt6muAaPBCoAgI85dPeT86XN0
    62vu5bd8xnv/OmfJ6FcfCqz4HH0SyiMyGlOeidWu3Ts=
    -----END CERTIFICATE-----
  nonce: AFCq1g+FaG4=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.0-2
    commit: 82f2cad
    build_time: "2023-09-10T15:23:01Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/6137985901
    compiler: go1.21.0
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  hostname: logger
  bind_address: 127.0.0.1
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 0.0.0.0
  bind_port: 9999
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQjCCAiqgAwIBAgIRAI9+XFYFvrIMFR1/kz8rUv8wDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIzMTAxNjA1MDI1NloXDTI0
    MTAxNTA1MDI1NlowKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH
    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm0/aF0kS8Ubl
    KmlRIkYhuWBplROSoGYoeMvXwI9bvWrTs/Fp49aXdQe3yWMhIqisamGkSyDxci7L
    IwcZlq5IiC+G5WNLs+8mbo3SpdK08AdmiWCjVbtRFfStxxkoxFTj3zTCEn02s/AC
    rAd4zsQlLd4GrG48v5jXIwJ5GoGPXfFLlUy59AU6O1pRyAKeuGouZAiJ4OgwdVVL
    aPjjG+JCe7cVH/JK12sclZs3N8mpeW1IpF97xhLF1NkqKbnbzuKSQpBb7pE+ZQtW
    A3zDhgc/6ga1+iHfqvOBkNKe+fcJzpdJUKxtffg7GkHqZbKxioOHQsRMMAkzVCXP
    6dghON5zVQIDAQABo3QwcjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUZi5aKA/a
    pJbEQQNZMT782wPXxUswEgYDVR0RBAswCYIHR1JQQ19HVzANBgkqhkiG9w0BAQsF
    AAOCAQEAgnVYTST28xjbYF0Ioq8eUGQzuJyNfk9CYxfFRzJsqhNN1gI7CwJmiJrB
    ZXn47fFoOgQmJxnhdAGk/DEvKpWPNHcf1nCkztvhWP+HsKrzGHNZo3ky1Efuf1nf
    +CgaNJNhzKeauQkcxBvThLhZpEMu8VWpNlbROGoqROGDcajMrla/fX31aIM7CR2U
    QktNLXEUiXy3EhFRGIjDW/Dw658O8l3e0/XHWB1aGqmnqItJSCD7XdzmckiaCYKb
    u3CkRZjNdLD/f+6bcI4IRIKTBuVmpu3hZXcViy79MWDjNhQyzHeT/8gE6MNvi2Z+
    5CuCypznJVIdvNTj9yjt8o24L4yVMg==
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAm0/aF0kS8UblKmlRIkYhuWBplROSoGYoeMvXwI9bvWrTs/Fp
    49aXdQe3yWMhIqisamGkSyDxci7LIwcZlq5IiC+G5WNLs+8mbo3SpdK08AdmiWCj
    VbtRFfStxxkoxFTj3zTCEn02s/ACrAd4zsQlLd4GrG48v5jXIwJ5GoGPXfFLlUy5
    9AU6O1pRyAKeuGouZAiJ4OgwdVVLaPjjG+JCe7cVH/JK12sclZs3N8mpeW1IpF97
    xhLF1NkqKbnbzuKSQpBb7pE+ZQtWA3zDhgc/6ga1+iHfqvOBkNKe+fcJzpdJUKxt
    ffg7GkHqZbKxioOHQsRMMAkzVCXP6dghON5zVQIDAQABAoIBAGiot7uHR5eFgbpB
    vCXPgrxL5vpJdT5XeSBlpN8i+9w5161jmkqpeeioKcYw4cxcQ8twPulNqsaaF9Nj
    3m92xHPZKxr6/bGkD47iTTfnNHynUAZ1M7v6/VpBRrVrE9ixp9jq0XjqHenFa9eH
    NXaIING202Jw6sjl8tupt/gPpI/VlKb2c9czi96Y4fdk4+WQEO8OD+l6Kn7EG9VQ
    Twl0trwE0oN+kyyoLXNhZpXAQmQEvRZCXtEODQ5CUrXgwSB6ZHsXXuSswPgaqq+o
    F1TzWog3tB6RNly/Nd/hcAORtTZO7vfdn+vQ1itvuH/dKrYbzKEb/rLApI1kM8ld
    uUKQt8ECgYEAyoDXl0/u9275hwjU0dJeRwXwRV8KnLuhmwAKEJEGpVb6YIZYhqiz
    /LxqDEJY4MrdBNwgDPHK5Z1gR1PUUOzbxvJFIjuAOz0GgjrolySbNqaRCDcnD9MO
    +vh4URGfftTVKWJmNKi+fea2zoLMJLmd0Jzp4b4s0wNNwRRA6us89FECgYEAxFd9
    deUxflLrzivJbzuYMtiFcuOwuOfnalqvC4aBiCqxYyAc3F1wx95YoE5xsXPvVIXr
    UQOodENHJQtbY7mNCNq/wzJ2dms72dDl+3wucvyBsYE201s7LVk2lG+jhArr5+Iw
    xoH4BZnDX0UI9LtjeXzBt5a8zjuWwE8QQtn4IcUCgYAwM9sduXk4jMH40rFWAK1Q
    WqmG2ci85izhqHC84MikMsAGmfQYma++SVs079YYLDHQJlW6vxN89KkmUV4IpVjr
    UmACdgdgEnaqKTuUPrJzn9KGEhrKOYMnWl3Jblh46FCVOUb64e/2KCT7o0bUtxpJ
    vhAuHAavc+neO+P4B2bLAQKBgC6ME1lM4cPyAqdZKCMvvLBpNpH7Ot1LVUiYgSE5
    XSIcBPvcFBuGJ4OqydYPYtLQCnA+Y4BMXrZZcNdubtcgmTf9LDMpln4ShBjqdmt9
    kEGAbXrYiFfpLAlfOhpMsTZPpIfPzwJws40YXAINCseCWV3m3sIYgWBfLikfVVqT
    9EiFAoGBAJpqQYHXj//iN3bO4PLo3Br84wJwWq6aVVuAcPOijDW6obXk/sJAAu0B
    vTqQZiJoDBEuHXyNkikR1kFHk5TYXbWwxysVRi21uswC6p7p/NWfuk4wpAGqQ+H1
    4Fv/6zbBUaedA7NHo5qm4kTnIp+iXfZiz7gMzNDq3xjisw3Ea2kt
    -----END RSA PRIVATE KEY-----
  initial_users:
  - name: admin
    password_hash: 1b7fb3a9255f498ff0755355912e6ee5ca218491417087b04a4953c90415e65a
    password_salt: 6e82c2611e99c200ee2dca4d7b3a4d599cfcfb3b023a226b2bb0c4f738a06246
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA4JpgvMSKzxD7kpY93u1QLvplZ2iWtZ12cW3SgeUfINjz3f12
    W9UF6tRkoajSMbJS/MMD4+qpBmMHVKnjqnQ4UiGb5AQY8esiJeqAvPUeOWGelMdv
    VwSEtNYkVats1S2HRn2DyJcEhX+2TMtNxWYGgh2NioXR+7hrLcX8cWwEHY6K13pq
    pQ87IfI9U9oMEWiV6jOah55XrRukn0swSV+dgvi4QByMwLtd6tDMdfJcs4qcwaca
    wfpyM1ayF+GOA8OptZIAvwH5Ti7wrLU6oQW/vwimWDpVPJ0BxB9+ie6Uc0Iu0ymH
    /kTD18/oP+ULxAT/B2Lb6NTommuttoDz8BT1kwIDAQABAoIBAGd1NRI+xmHTRM6k
    /iLt1X2OQZ98gc9ulNxy5gCHdes/hDXBRv/OBEfDRgdhKFFT/v4HJoeZ0/npK7tH
    9mLR3g+XA6Pob0UgNj6Y4mwnzKBJ4y5NH3BJ2IckDOCZcixQKHvD3SxMw/xqc6K0
    E0LWWDEfQ8+HDM6SiGwxQrNMOikSXqQA+NoxOD/k4ye0IAMpgUbWnA0uArSQh0gw
    k51FdRC1uwtK43loRAHM/4/giemImRnXjYpKKxgf0uK6xjOeD0GWVVEYQMQV3CFb
    nigCR3CYLXO64ZZkHaiiTMXwWE3Uar2SJFC5TP9EuyzZKTDX93ZYURLUqr0gRdrw
    LCSt8aECgYEA5Nu4gM5SSRJB0b6zC9/P94w017uLIvQGxqPS4ZodzEyWHD5JxaYb
    Iq31g/hohvzgsQebHYb7aMEm6Fz7tT1zVaLJiXlJPZi1qWpvVJHshyz37cMKBOnf
    jpmx1jZyiJo8yejZ/gbOxAlc1Gw5UPUe1ls+p5pyPLUqUHc+JYhNoycCgYEA+z13
    HGNJw4vlt8N+hMvJfqX52hGPqYY09Rw0Zk/LhAY6WPiUnIfruh4mVpgQSBOnN/5s
    8KFWcGBJIp1faTBhvUPATOBRsznPb219f7kjvbgX/yOEdcLMv2nK7X0P2pw6nG08
    w8b5diayWlWvrmBOu+chqkoyy8QOJwxlg9cfbbUCgYEAw6YfbmZ0LCnigQhRkvYs
    mYmQZ1nakfAiltDY6KtTjCNxNQX/FWxyyEwFl2PXIIexI0bIUg7igWSW+ZD8Uq4N
    GonHV7KLbZBOxV3LfXYeylUkQ2w49Yhm6Ub1pJb5hVSuYUKikiuJukfyx1saCN71
    FPX+c1RzEvkiCpZWV8nV7YMCgYBOXpb4EPSifdITZ3TgwZzB184/OrkgfU+pobmq
    rHtkXHj45dmdljxu2xbEbjyt7wt7SO78hKcs+Kv3kzV+32utmSO0F0kE6iSNso6y
    N7Mxa+p4WMDp5vDtSHfXaup2G8OgpeaNf1SziVCbIx1g/IOy019J+kksDKUJgzFr
    VcBk/QKBgQCljB0urWP2CoX/ffjePd1BTAc/hqEst1jRV4PmHV0KEdc06zmLH4NI
    H2p0Qe3QRIlzSfVS1u22iwENbKL1xHJiHf4AYrKO+/OisUGV+jJa1n+WU/UQUX6U
    2h651JxfF5zXMxUgOUfMsiM9jbfSh+5iaKjz2Qd0CVbhJ43x5EXfWA==
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: logger
  bind_address: 0.0.0.0
  bind_port: 9000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDWDCCAkCgAwIBAgIRAPTB7Q7gA0sk2MyiM6tU+p0wDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIzMTAxNjA1MDI1NloXDTI0
    MTAxNTA1MDI1NlowNDEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRswGQYDVQQDExJW
    ZWxvY2lyYXB0b3JTZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDI2lKnVt5BNF8lXdCeLtDKq1vLILh/Cu8waf55+k29r/EYaQtLh2/caw1fPMLU
    scC6EbKOcPkg8HlHVtt3xID+C+QLbgep3XKpfa/Imq2DLkH/32ziNuSDNGqdESL7
    3qF/nbspDuLF3RLcrFWEVUEz44PO654vmAJMA1rC+Htdr0PJYzCcA5pp2JTJ33ft
    JkdESQVY6pLQbknGTOj+hjBxJOu46sZTbChqs/dV3H9Fw+CgkxTM85bs4rUiTpjh
    ktY6bgKMUdBQWNL3jmOjnuQPOyTa5qDMYPrla4r87sgABMv5Yru0jcoQglr8nUPE
    17uUeNH/kCZsU+kr54/4Yi6fAgMBAAGjfzB9MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSME
    GDAWgBRmLlooD9qklsRBA1kxPvzbA9fFSzAdBgNVHREEFjAUghJWZWxvY2lyYXB0
    b3JTZXJ2ZXIwDQYJKoZIhvcNAQELBQADggEBABSYk676JP/fz93H6Zq1V4cSNJyY
    qQNTlFRT9Kwji3pp7xyLJbwv/Bx102Xqh78clmUOiKgukh/gccfjLivQPCHVLXMV
    yVk0JV9oxBr57u2MIrhf7w2hiL0MxJ7vOFXPnnasppufY2E+UJabzzFvYqZ5eOc1
    a5pYG7lPnEcdD8w2FhsryXsWgvLdlYkP1TxDK5dsgXo3GlcWq+W9AiMAO6oXgpTW
    UUo6aKio9FovBCD01uaFoBqNm/6jit8S5lryFnWdQufEvt8aHjvX4ScjVV7Da5zq
    XG4aR74JWQC+toda6xPS4TLnaIgt1GHC7I3wHDFBqZ9Va1sgatBUsKvvVtA=
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAyNpSp1beQTRfJV3Qni7QyqtbyyC4fwrvMGn+efpNva/xGGkL
    S4dv3GsNXzzC1LHAuhGyjnD5IPB5R1bbd8SA/gvkC24Hqd1yqX2vyJqtgy5B/99s
    4jbkgzRqnREi+96hf527KQ7ixd0S3KxVhFVBM+ODzuueL5gCTANawvh7Xa9DyWMw
    nAOaadiUyd937SZHREkFWOqS0G5Jxkzo/oYwcSTruOrGU2woarP3Vdx/RcPgoJMU
    zPOW7OK1Ik6Y4ZLWOm4CjFHQUFjS945jo57kDzsk2uagzGD65WuK/O7IAATL+WK7
    tI3KEIJa/J1DxNe7lHjR/5AmbFPpK+eP+GIunwIDAQABAoIBAQCbQkjKGhhMBxPV
    aqOs4zt6ruOSLYTwj589qXGREK+vhaW03N5iUBtkI0x+5hUlHRKBwtRnz2SE1d6q
    CrYz6q5bsw1g2HkMEaZk5kdPpmGiGcvi4u7kHtKdqZMQPwLv97SXVXIr1tntYWsH
    MiAY3147og9tkC0DVVnRMHakaDfUvhm+oTbFTZlEUdIeMxmFw8M1S/4ECzZNo3iS
    /NG1rpAiLDi2wFxP8lQvieXU0ZuQS2fF8Q2UWy0PHogKFVDhxbM83YHzUyJloeLH
    Znk3EJ6sQecLyRjRZHGiZbY/dEnc7hdvwD9bm/ZW/4HkypS/KhzwFsHoKViIZ3hQ
    YqQ5C31BAoGBAP2jVRI9KE/hOr9c7l/SdHv9zqVCq57kK1Hzg5x23+UMrqQ6sl3i
    JlalrL4H/W64wGCc/dBMEYbhyhIs3VHc8PC0nht4yAaRArEv4FnFOi0gYcvqu9Nj
    ab3EeocALqLF+h76jsCN8zRvKMCDoQo/et+jvMFYYDm0eo7W18vxdg25AoGBAMq5
    Jto9R9faxH08Pfdf8DpH4HSVOAxbORfEnB5zjmnexS1NTIuH8EbLZ7HIAJOAoNGl
    85CEo45sv4qEld5Wr1VPEjAKreupSE3Wl0FTcE7kLG1YTgfqJFGw++MTCGvOFVOF
    xdtGe8UOP9O8K+Za5o0EV8wtH6EcrCHgqLxtsAsXAoGBAObwiM0KkmHpGayT2Re2
    cAlVl4oxokISTr9XkkYslr/fRESUjUOeXnoWb6q3a7Ic1k0hpJi8Klk9zNevsfSP
    z3HbgvpQhxAziNf8V7JlOgtMqL8bA9n9cpIvC8FQESZ0TMFYMhJxLThY3iorr728
    /wwR8hO5fCQOiGj2hZZUTMFBAoGAKSiyZLjwbzjxj+O9SQ5nfc2+Gq15NbkHvHWk
    pOIdVg1uxyXclq/A7v65TPUoeMoy3J3u97aWZoJZ2UvWCdBbxNxK+woQCbrS/UrG
    ZvMD6GCXTJQTM7QsL5HZcl8Y5Jpw5gZRB5Yl5vpfpyObXieyi4sIMGIw+8sQf8hX
    OfqjNX0CgYAG5h/xFkby52KWf83I6xnbSRLwiSfGi1PdhXzZehkEAewAiGk87UkY
    eMLo30H7QNsv4BJ4zyENv+/xRLOG16BipctFT3Vl3h+F0x27f91xOdzkoH85+3vG
    hEaI/hTSZDxSg4u80Ujp/hCKtlvuf+M7WPm82YI0sjxYc+VPZYUyog==
    -----END RSA PRIVATE KEY-----
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  run_as_user: velociraptor
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: /opt/velociraptor
  filestore_directory: /opt/velociraptor
Writeback: {}
Mail: {}
Logging:
  output_directory: /opt/velociraptor/logs
  separate_logs_per_component: true
  debug: {}
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
server_type: linux
obfuscation_nonce: fxeE5g10I6s=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
